### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by sruin** [triforce/shhchat#44]
你好！我是一名即将毕业的计算机专业的本科生，最近在做毕业设计，在github上看到了您发布的这个聊天程序，对此很感兴趣。想利用这个来完成我的毕设，能给予我一些帮助吗？

**Comment by triforce** [comment]
If you could ask the question in English that would be most helpful so I can help you.

**Comment by sruin** [comment]
I am sorry !  I come from China，I‘m a senior student . I’m majoring in CS. Recently I‘m interested ssl. So  I want to chose your project as my graduation project of this topic. I can test shhchat and give you some advice .So can you help me?

**Comment by triforce** [comment]
Sure what do you need help with? Feel free to make a pull request.

**Comment by sruin** [comment]
If I do this project with your “readme.cmd",can I run this program successfully？ Or I have to do something else before run the program. Could you please give more advice? Thank you

**Comment by triforce** [comment]
Yes it should be fine and if not please let me know or create a pull request.

**Comment by sruin** [comment]
I meet a problem. I can't create the server cert when I input "openssl x509 -req -in server.req -CA ../ca.pem -CAkey ../privkey.pem -CAserial serial.srl -out server.pem", there are"Signature ok" ,But after I Enter pass phrase for ../privkey.pem: The problem is"unable to load number from serial.srl" Before that I create server.key and server.req successfully.

**Comment by triforce** [comment]
There is a script in scripts/create_certs.sh that will create some simple SSL certs for you. I can't really help debug your problems without a full transcript of what commands you have run.

You need to compile the server and client using the Makefile to create the binaries before you can run the server and client as per README instructions.

**Comment by sruin** [comment]
OK I know that, Thank you very much

**Comment by sruin** [comment]
I sorry for troubling you again! Before I run the server,there is a problem"undefined reference to symbol 'OPENSSL_add_all_algorithms_noconf@@OPENSSL_1.0.0" and "error adding symbols: DSO missing from command line" Do you have this problem when you run the server? Thank you!..

**Comment by triforce** [comment]
Do you have the libcrypto and libssl libraries installed on your OS?
